import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import {
  parseEnvironmentFile,
  validateDeploymentRuntimeProfile,
} from "./check-runtime-profile.mjs";

test("deployment preflight parses dotenv without exposing values", () => {
  assert.deepEqual(
    parseEnvironmentFile(`
      # generated by deployment provider
      APP_ENV="production"
      PERSISTENCE_DRIVER=supabase
      export AUTH_DRIVER='supabase'
    `),
    {
      APP_ENV: "production",
      PERSISTENCE_DRIVER: "supabase",
      AUTH_DRIVER: "supabase",
    },
  );
});

test("deployment preflight accepts only an explicit durable profile", () => {
  assert.deepEqual(
    validateDeploymentRuntimeProfile(
      {
        APP_ENV: "production",
        PERSISTENCE_DRIVER: "supabase",
        AUTH_DRIVER: "supabase",
        SUPABASE_URL: "https://project.example.test",
        SUPABASE_SECRET_KEY: "unit-test-key",
        CORS_ALLOWED_ORIGINS:
          "https://waiter.example.test,https://cash.example.test",
      },
      "production",
    ),
    {
      environment: "production",
      persistenceDriver: "supabase",
      authenticationDriver: "supabase",
      durable: true,
      supabaseUrlConfigured: true,
      serverCredentialConfigured: true,
      corsAllowedOriginCount: 2,
    },
  );
});

test("deployment preflight rejects missing, mismatched and ephemeral profiles", () => {
  const valid = {
    APP_ENV: "production",
    PERSISTENCE_DRIVER: "supabase",
    AUTH_DRIVER: "supabase",
    SUPABASE_URL: "https://project.example.test",
    SUPABASE_SECRET_KEY: "unit-test-key",
    CORS_ALLOWED_ORIGINS: "https://waiter.example.test",
  };
  for (const [field, value, message] of [
    ["APP_ENV", "preview", /APP_ENV must equal production/],
    ["PERSISTENCE_DRIVER", "memory", /PERSISTENCE_DRIVER/],
    ["AUTH_DRIVER", "fixture", /AUTH_DRIVER/],
    ["SUPABASE_URL", "", /SUPABASE_URL/],
    ["SUPABASE_SECRET_KEY", "", /server-side Supabase secret/],
    ["CORS_ALLOWED_ORIGINS", "", /CORS_ALLOWED_ORIGINS/],
  ]) {
    assert.throws(
      () =>
        validateDeploymentRuntimeProfile(
          { ...valid, [field]: value },
          "production",
        ),
      message,
    );
  }
});

test("deployment preflight rejects wildcard and non-origin CORS values", () => {
  const valid = {
    APP_ENV: "demo",
    PERSISTENCE_DRIVER: "supabase",
    AUTH_DRIVER: "supabase",
    SUPABASE_URL: "https://project.example.test",
    SUPABASE_SECRET_KEY: "unit-test-key",
  };
  for (const value of [
    "https://*.example.test",
    "https://example.test/path",
    "https://user:password@example.test",
    "not-a-url",
  ]) {
    assert.throws(
      () =>
        validateDeploymentRuntimeProfile(
          { ...valid, CORS_ALLOWED_ORIGINS: value },
          "demo",
        ),
      /CORS_ALLOWED_ORIGINS/,
    );
  }
});

test("Vercel production workflows validate Maitre's logical demo environment", () => {
  for (const workflow of ["deploy.yml", "e2e.yml"]) {
    const contents = readFileSync(
      new URL(`../../.github/workflows/${workflow}`, import.meta.url),
      "utf8",
    );
    assert.match(contents, /--expect demo/);
    assert.doesNotMatch(contents, /--expect production/);
    assert.match(contents, /check-deployment-health\.mjs/);
    assert.match(
      contents,
      /MAITRE_API_HEALTH_URL: https:\/\/maitre-api\.vercel\.app/,
    );
    assert.match(
      contents,
      /check-deployment-health\.mjs "\$MAITRE_API_HEALTH_URL"/,
    );
    assert.doesNotMatch(
      contents,
      /check-deployment-health\.mjs "\$deployment_url"/,
    );
  }
});
